# Generated by Django 5.2.7 on 2025-10-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencing', '0003_auto_20250224_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
